---
es_config:
  cluster.initial_master_nodes: "es-node-01"
  http.port: "{{ mc_es_http_port | default('9220') }}"
  network.host: "{{ mc_es_network_host | default('_eth0_') }}"
  node.roles: "{{ mc_es_node_roles }}"
  transport.host: 0.0.0.0
  transport.port: "{{ mc_es_transport_port | default('9320') }}"

es_data_dirs: ["/usr/share/elasticsearch/data"]
es_heap_size: "1g"
es_log_dir: "/var/log/elasticsearch"
es_templates: false
es_templates_fileglob: ""

mc_es_seed_hosts:
  - es-node-01
  - es-node-02
  - es-node-03
elasticsearch_nodes:
  - name: es-node-01
    mc_es_http_port: 9229
    mc_es_transport_port: 9329
  - name: es-node-02
    mc_es_http_port: 9230
    mc_es_transport_port: 9330
  - name: es-node-03
    mc_es_http_port: 9231
    mc_es_transport_port: 9331
