---
# include_tasks file

# NOTE! Add as pre-task to properly load env variables, solve variables order
- name: Load Elasticsearch role defaults
  ansible.builtin.include_vars:
    dir: ../roles/elasticsearch/defaults
  tags: always

- name: Ensure group_vars are loaded
  ansible.builtin.include_vars:
    dir: ../inventories/group_vars
  tags: always

- name: Store base es_config from group_vars
  ansible.builtin.set_fact:
    base_es_config: "{{ es_config | default({}) }}"
  tags: always

- name: Combine es_config values properly
  ansible.builtin.set_fact:
    es_config: "{{ base_es_config | combine(lookup('vars', env + '_es_config') | default({}), recursive=True) }}"
  tags: always

- name: Source private env variables
  ansible.builtin.include_tasks:
    file: "source-envs.yml"
