---
es_version: "8.17.3"
es_major_version: "8.x"
es_use_snapshot_release: false
oss_version: false
es_package_name: "elasticsearch"
es_version_lock: true
es_use_repository: true
es_add_repository: true
es_templates_fileglob: ""
es_repo_base: "https://artifacts.elastic.co"
es_apt_key: "{{ es_repo_base }}/GPG-KEY-elasticsearch"
es_apt_url: "deb {{ es_repo_base }}/packages/{{ es_repo_name }}/apt stable main"
es_apt_url_old: "deb http://packages.elastic.co/elasticsearch/{{ es_repo_name }}/debian stable main"
es_start_service: true
es_java: openjdk-21-jre-headless # Ubuntu 22.04 specific
es_java_install: true
update_java: false
es_restart_on_change: true
es_plugins_reinstall: false
es_templates: false
es_user: elasticsearch
es_group: elasticsearch
es_home: "/usr/share/elasticsearch"
es_config: {}
es_config_default: "elasticsearch.j2"
es_config_log4j2: ""
es_config_jvm: "jvm.options.j2"
#Need to provide default directories
es_conf_dir: "/etc/elasticsearch"
es_pid_dir: "/var/run/elasticsearch"
es_tmp_dir: "/tmp"
es_action_auto_create_index: true
es_max_open_files: 65536
es_max_map_count: 262144
es_allow_downgrades: false
#These are used for internal operations performed by ansible.
#They do not affect the current configuration
es_api_scheme: "http"
es_api_host: "localhost"
es_api_port: "{{ mc_es_http_port }}"
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_api_sleep: 15
es_debian_startup_timeout: 10
default_file: "/etc/default/elasticsearch"
host_key_checking: false

# JVM custom parameters
es_java_home: ''
es_jvm_custom_parameters: ''
es_heap_dump_path: "/var/lib/elasticsearch"

m_lock_enabled: true
sysd_config_file: "/etc/systemd/system/elasticsearch.service.d/override.conf"
