---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

  vars:
    es_config:
      cluster.initial_master_nodes: "{{ mc_es_seed_hosts }}"
      discovery.seed_hosts: "{{ mc_es_seed_hosts }}"
      http.port: "{{ mc_es_http_port | default('9200') }}"
      network.host: "{{ mc_es_network_host | default('0.0.0.0') }}"
      node.roles: "{{ mc_es_node_roles }}"
      transport.port: "{{ mc_es_transport_port | default('9300') }}"
      bootstrap.memory_lock: true
      xpack.security.enabled: false

    es_data_dirs: ["/usr/share/elasticsearch/data"]
    es_heap_size: "1g"
    es_log_dir: "/var/log/elasticsearch"
    es_templates: false
    es_templates_fileglob: ""
    es_version: "8.17.3"

    mc_es_seed_hosts:
      - "es-node-01"
      - "es-node-02"
      - "es-node-03"
    mc_es_node_roles: "master,data"
    elasticsearch_nodes:
      - name: es-node-01
        mc_es_http_port: 9229
        mc_es_transport_port: 9329
      - name: es-node-02
        mc_es_http_port: 9230
        mc_es_transport_port: 9330
      - name: es-node-03
        mc_es_http_port: 9231
        mc_es_transport_port: 9331
