---
- name: Configure Elasticsearch
  hosts: "{{ target | default('localhost') }}"
  become: false

  pre_tasks:
    - name: Source all env variables
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/../tasks/load-envs.yml"

  tasks:
    - name: Check if environment is staging or dev
      ansible.builtin.set_fact:
        is_staging_or_local: "{{ env == 'staging' or env == 'local' }}"
      tags: always

    - name: Ensure Elasticsearch is accessible (production)
      ansible.builtin.uri:
        url: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}/_cluster/health"
        method: GET
        status_code: 200
        headers:
          Content-Type: "application/json"
      register: es_info
      until: es_info.status == 200
      retries: 6
      delay: 10
      when: not is_staging_or_local | bool
      tags: always

    - name: Ensure Elasticsearch is accessible (staging or local)
      ansible.builtin.uri:
        url: "{{ es_api_scheme }}://{{ es_api_host }}:{{ node.mc_es_http_port }}/_cluster/health"
        method: GET
        status_code: 200
        headers:
          Content-Type: "application/json"
      register: health_check
      until: health_check.status == 200
      retries: 6
      delay: 10
      loop: "{{ docker_elasticsearch_nodes }}"
      loop_control:
        loop_var: node
      when: is_staging_or_local | bool
      tags: always

    - name: Configure ILM policies
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../roles/elasticsearch"
        tasks_from: create-ilm-policy.yml
      tags: es_ilm

    - name: Create index template
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../roles/elasticsearch"
        tasks_from: create-index-template.yml
      tags: es_template

    - name: Create initial index
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../roles/elasticsearch"
        tasks_from: create-initial-index.yml
      tags: es_index

    - name: Configure Elasticsearch keystore
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../roles/elasticsearch"
        tasks_from: configure-elasticsearch-keystore.yml
      tags: es_slm

    - name: Create snapshot repository
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../roles/elasticsearch"
        tasks_from: create-snapshot-repository.yml
        apply:
          become: true
      tags: es_slm

    - name: Create SLM policy
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../roles/elasticsearch"
        tasks_from: create-slm-policy.yml
      tags: es_slm
