---
- name: Install and configure Elasticsearch cluster
  hosts: elasticsearch
  become: true

  roles:
    - role: ../roles/elasticsearch
      tags:
        - elasticsearch

  pre_tasks:
    - name: Check OS compatibility
      fail:
        msg: "This playbook is only compatible with Debian and Ubuntu. Detected OS: {{ ansible_distribution }}"
      when: ansible_distribution not in ['Debian', 'Ubuntu']
      tags:
        - always

    - name: Display OS version
      ansible.builtin.debug:
        msg: "Running on OS {{ ansible_distribution_version }}"
      tags:
        - always

    - name: Set Elasticsearch major version fact
      ansible.builtin.set_fact:
        es_major_version: "{{ es_version.split('.')[0] }}.x"
      when: es_major_version is undefined
      tags:
        - always

  post_tasks:
    - name: Install statsd agent
      ansible.builtin.include_tasks:
        file: "../tasks/install-statsd-agent.yml"
