---
- name: Configure Data Re-Indexing from Remote Cluster
  hosts: elasticsearch
  become: false

  vars:
    # Default values that can be overridden via extra vars on playbook run
    reindex_date_from: "{{ mc_reindex_date_from }}"
    reindex_date_to: "{{ mc_reindex_date_to }}"
    source_index: "{{ source_index }}"
    dest_index: "{{ dest_index }}"
    es_reindex_batch_size: "{{ es_reindex_batch_size }}"

  tasks:
    - name: Load Elasticsearch role defaults
      ansible.builtin.include_vars:
        file: ../roles/elasticsearch/defaults/main.yml
      tags: always

    - name: Display reindexing parameters
      ansible.builtin.debug:
        msg:
          - "Re-indexing Configuration:"
          - "  - Source Index: {{ source_index }}"
          - "  - Destination Index: {{ dest_index }}"
          - "  - Date Range: {{ reindex_date_from }} to {{ reindex_date_to }}"
          - "  - Batch Size: {{ es_reindex_batch_size }}"
      tags: always

    - name: Ensure Elasticsearch is accessible
      ansible.builtin.uri:
        url: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}/"
        method: GET
        status_code: 200
        timeout: 30
        headers:
          Content-Type: "application/json"
      register: es_info
      until: es_info.status == 200
      retries: 5
      delay: 10
      tags: always

    - name: Execute Elasticsearch reindexing tasks
      ansible.builtin.include_role:
        name: ../roles/elasticsearch
        tasks_from: elasticsearch-reindex
      vars:
        es_reindex_batch_size: "{{ es_reindex_batch_size }}"
        source_index: "{{ source_index }}"
        dest_index: "{{ dest_index }}"
        reindex_date_from: "{{ reindex_date_from }}"
        reindex_date_to: "{{ reindex_date_to }}"
      tags: es-reindex
