---
- name: Stop and delete Elasticsearch
  hosts: staging
  become: true

  tasks:
    - name: Stop Elasticsearch service
      ansible.builtin.service:
        name: elasticsearch
        state: stopped
      tags:
        - stop

    - name: Remove Elasticsearch package
      ansible.builtin.package:
        name: elasticsearch
        state: absent
      tags:
        - remove

    - name: Remove Elasticsearch configuration files
      ansible.builtin.file:
        path: "{{ es_conf_dir }}"
        state: absent
      tags:
        - remove

    - name: Remove Elasticsearch data directory
      ansible.builtin.file:
        path: "{{ es_data_dirs | default('/var/lib/elasticsearch') }}"
        state: absent
      tags:
        - remove

    - name: Remove Elasticsearch logs directory
      ansible.builtin.file:
        path: "{{ es_logs_dir | default('/var/log/elasticsearch') }}"
        state: absent
      tags:
        - remove

    - name: Remove Elasticsearch user and group
      ansible.builtin.user:
        name: elasticsearch
        state: absent
        remove: true
      tags:
        - remove
