---
# COULD be a general inventory.yml file...
# to check this file run "venv/bin/ansible-inventory -i inventories/hosts.yml --list"

# used by es-test-vars.yml/sh
all:
  children:
    elasticsearch:
      hosts:
        es01:
          ansible_host: es01.newsscribe.angwin
        es02:
          ansible_host: es02.newsscribe.angwin
        es03:
          ansible_host: es03.newsscribe.angwin
        es04:
          ansible_host: es04.newsscribe.angwin
        es05:
          ansible_host: es05.newsscribe.angwin
        es06:
          ansible_host: es06.newsscribe.angwin
        es07:
          ansible_host: es07.newsscribe.angwin
        es08:
          ansible_host: es08.newsscribe.angwin
