---
- name: Load initial index template from file
  ansible.builtin.include_vars:
    file: "./files/templates/initial_index.json"
    name: initial_index_data

- name: Check if index exists
  ansible.builtin.uri:
    url: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}/{{ initial_index_data.name }}"
    method: HEAD
    status_code: [200, 404]
  register: index_status
  failed_when: false

- name: Set fact for index existence
  ansible.builtin.set_fact:
    index_exists: "{{ index_status.status == 200 }}"

- name: Create initial index
  ansible.builtin.uri:
    url: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}/{{ initial_index_data.name }}"
    method: PUT
    body:
      aliases: "{{ initial_index_data.aliases }}"
    body_format: json
    status_code: [200, 400]
  register: index_creation
  when: not index_exists
  failed_when: >
    index_creation.status != 200 and
    (index_creation.json.error.type != 'resource_already_exists_exception')
  tags: create_index

- name: Print index creation status
  ansible.builtin.debug:
    msg: "Index '{{ initial_index_data.name }}' already exists. Skipping creation."
  when: index_exists

- name: Print index creation result
  ansible.builtin.debug:
    msg: "Index created successfully."
  when: not index_exists and index_creation.json.acknowledged | default(false)
