- name: Create SLM policy
  ansible.builtin.uri:
    url: '{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}/_slm/policy/{{ sourced_env.ELASTICSEARCH_NEWSSCRIBE_SNAPSHOT_REPO }}'
    method: PUT
    body: "{{ lookup('template', '../roles/elasticsearch/templates/bi_weekly_slm_policy.json.j2') }}"
    body_format: json
    status_code: 200
    timeout: 30
    headers:
      Content-Type: 'application/json'
  register: slm_creation
  retries: 6
  delay: 10
  until: slm_creation.status == 200
  when: not ansible_check_mode

- name: Run SLM policy manually
  ansible.builtin.uri:
    url: '{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}/_slm/policy/{{ sourced_env.ELASTICSEARCH_NEWSSCRIBE_SNAPSHOT_REPO }}/_execute'
    method: POST
    status_code: 200
    headers:
      Content-Type: 'application/json'
  register: slm_execution
  when: not ansible_check_mode

- name: Get SLM policy execution results
  ansible.builtin.assert:
    that:
      - slm_execution.status == 200
      - slm_execution.json is defined
    success_msg: 'SLM policy executed successfully: manual snapshot creation initiated.'
    fail_msg: 'SLM policy execution failed: received unexpected status or missing response content.'
  when: not ansible_check_mode
