---
- name: Set es_api_port for dev/staging (first node)
  ansible.builtin.set_fact:
    es_api_port: "{{ docker_elasticsearch_nodes[0].mc_es_http_port }}"
  when: is_staging_or_local | bool
  tags: always

- name: Create or update index template using Elasticsearch API
  ansible.builtin.uri:
    url: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}/_index_template/{{ mc_index_template_name }}"
    method: PUT
    body: "{{ lookup('template', '../roles/elasticsearch/templates/index.template.json.j2') }}"
    body_format: json
    status_code: [200, 201]
    headers:
      Content-Type: "application/json"
  register: template_creation
  retries: 6
  delay: 10
  until: template_creation.status in [200, 201]
  when: not ansible_check_mode

- name: Get index template for validation
  ansible.builtin.uri:
    url: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}/_index_template/{{ mc_index_template_name }}"
    method: GET
    status_code: 200
    timeout: 30
    headers:
      Content-Type: "application/json"
  register: template_validation
  when: not ansible_check_mode

- name: Validate template configuration
  ansible.builtin.assert:
    that:
      - template_validation.status == 200
      - template_validation.json is defined
      - template_validation.json.index_templates is defined
      - template_validation.json.index_templates | length > 0
    success_msg: "Index template '{{ mc_index_template_name }}' successfully configured"
    fail_msg: "Failed to validate index template '{{ mc_index_template_name }}'"
  when: not ansible_check_mode
