---
- name: Create or update index template using Elasticsearch API
  ansible.builtin.uri:
    url: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}/_index_template/{{ mc_index_template_name }}"
    method: PUT
    body: "{{ lookup('template', '../roles/elasticsearch/templates/index.template.json.j2') }}"
    body_format: json
    status_code: [200,201]
    timeout: 30
    headers:
      Content-Type: "application/json"
  register: template_creation
  retries: 3
  delay: 5
  until: template_creation.status in [200, 201]
  tags: es_templates

- name: Validate template creation
  ansible.builtin.assert:
    that:
      - template_creation.status in [200, 201]
      - template_creation.json.acknowledged | default(false)
    success_msg: "Index template '{{ mc_index_template_name }}' successfully configured"
    fail_msg: "Failed to configure index template '{{ mc_index_template_name }}'"
  tags: es_template
