---
- name: Update the server and install required packages
  ansible.builtin.apt:
    name: apt-transport-https
    update_cache: yes
    state: present
  tags:
    - packages

- name: check-set-parameters
  ansible.builtin.import_tasks: elasticsearch-parameters.yml
  tags:
      - always

- name: Install Java
  ansible.builtin.import_tasks: java.yml
  when: es_java_install | default(true)
  tags:
    - java

- name: Add ElasticSearch GPG key
  ansible.builtin.apt_key:
    url: "{{ es_apt_key }}"
    state: present
    keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
  tags:
    - repository

- name: Add ElasticSearch repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/{{ es_major_version }}/apt stable main"
    state: present
    filename: "elastic-{{ es_major_version }}"
  tags:
    - repository

- name: Install ElasticSearch
  ansible.builtin.apt:
    name: elasticsearch
    state: present
    update_cache: yes
  tags:
    - install

- name: Generate Elasticsearch configuration
  ansible.builtin.import_tasks: elasticsearch-config.yml
  notify: Restart elasticsearch
  tags:
    - config

- name: Start Elasticsearch service
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes
  tags:
    - service

- name: Wait for Elasticsearch to start
  ansible.builtin.uri:
    url: "{{ es_api_uri }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 6
  delay: 5
  changed_when: false
  tags:
    - verify
