---
# COULD be a general inventory.yml file...
# to check this file run "venv/bin/ansible-inventory -i es-inventory.yml --list"

# used by es-test-vars.yml/sh
local:
  hosts:
    host1:
    host2:
      mc_es_network_host: _bar_
  vars:
    mc_es_network_host: _foo_
    mc_es_seed_hosts:
      - host1

# TEMP FOR TESTING w/ docker container
elasticsearch:
  hosts:
    docker-container:
      ansible_host: ifill.angwin
      ansible_port: 2222
      ansible_user: phil
      ansible_become_password: philpassword
      become: true  # this may not have worked...
      mc_es_network_host: _foo_
  vars:
    mc_es_seed_hosts:
#     - docker-container

es:
  hosts:
    es01.newsscribe.angwin:
      # host specific settings here ...
    es02.newsscribe.angwin:
    es03.newsscribe.angwin:
    es04.newsscribe.angwin:
    es05.newsscribe.angwin:
    es06.newsscribe.angwin:
    es07.newsscribe.angwin:
    es08.newsscribe.angwin:
  vars:
    # defaults for all members of group.
    # see es-vars.yml for all other defaults
    mc_es_network_host: _eno8303_    # can override per host above, as needed
    mc_es_seed_hosts:
      - es01.newscribe.angwin
      - es02.newscribe.angwin
      - es03.newscribe.angwin
