# TEMPLATE VARIABLES: PLEASE KEEP SORTED!!
es_data_dirs: ["/data/elasticsearch/data"]
es_heap_size: 32767m    # 1m short of 32g
es_java: openjdk-21-jre-headless
es_java_install: true
es_log_dir: "/data/elasticsearch/logs"
es_start_service: false   # TEMP?
es_templates: false
es_templates_fileglob: ""
es_version: 8.17.2
es_version_lock: true

host_key_checking: false

mc_es_network_host: _eno8303_ # override by setting per-host
# PLEASE ADD ITEMS IN SORTED ORDER!
