---
- name: reload systemd configuration
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: restart elasticsearch
  become: true
  ansible.builtin.service:
    name: elasticsearch
    state: restarted
    enabled: yes
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted

- name: wait for elasticsearch to start
  wait_for:
    host: "{{ mc_es_network_host | default('localhost') }}"
    port: "{{ mc_es_http_port | default(9200) }}"
    delay: 10
    timeout: 60
  when: es_restarted is defined and es_restarted.changed
