# TEMPLATE VARIABLES: PLEASE KEEP SORTED!!
# DANGER! Anythig added here crushes per-host/group vars from es-inventory.yml!!

# NOTE! variables expanded lazily (when variable referenced/expanded)
# so values can come from:
# * es-inventory.yml (per-group, or per-node)
# * here, or another vars file (overrides inventory)
# * "set_fact" in playbook
# [IMO it's the ONLY thing about ansible that's better than shell scripts! -phil]

#### vars for ansible-elasticsearch (all start with es_)
# key/values copied to elasticsearch.yml output file:
es_config:
  # PLEASE ADD ITEMS IN SORTED ORDER BELOW THIS LINE!
  bootstrap.memory_lock: true
  cluster.name: "mc_es_cluster"
  cluster.initial_master_nodes: "{{ mc_es_initial_master_nodes }}"
  # seed hosts is list of master-elibile nodes; port is defaulted from transport.port
  # (NOTE! if you add ports to mc_es_seed_hosts you'll break the mc_es_master test below)
  discovery.seed_hosts: "{{ mc_es_seed_hosts }}"
  http.host: 0.0.0.0 # allow from off-host connections
  # to override, set in es-inventory group vars section:
  http.port: "{{ mc_es_http_port | default('9200') }}"
  # must be set per-host in es-inventory:
  network.host: "{{ mc_es_network_host | default('_eno8303_') }}"
  # node.name defaults to inventory_hostname
  node.roles: "{{ mc_es_node_roles }}"
  # to override, set in es-inventory group vars section:
  transport.port: "{{ mc_es_transport_port | default('9300') }}"
  # PLEASE ADD ITEMS ABOVE IN SORTED ORDER!

  # Disable X-Pack features
  xpack.security.enabled: false
  xpack.monitoring.enabled: false
  xpack.ml.enabled: false

es_data_dirs: ["/data/elasticsearch/data"]
es_heap_size: 32767m    # 1m short of 32g
es_java: openjdk-21-jre-headless # Ubuntu 22.04 specific
es_java_install: true
es_log_dir: "/data/elasticsearch/logs"
es_start_service: false   # TEMP?
es_templates: false
es_templates_fileglob: ""
es_version: 8.17.2
es_version_lock: true

# quiet ssh complaints (ansible setting, not ES specific)
host_key_checking: false

################ MC specific vars (start with mc_)

# elastic search specific vars (just about everything) should start with mc_es_

mc_es_master: "{{ inventory_hostname in mc_es_seed_hosts }}"
mc_es_node_roles: "{% if mc_es_master %}{{ mc_es_node_roles_master }}{% else %}{{ mc_es_node_roles_data }}{% endif %}"

mc_es_node_roles_data: ["data"]
mc_es_node_roles_master: ["master"]

# PLEASE KEEP THIS FILE IN SORTED ORDER!
# (KEEP THIS LINE LAST!)
